language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - phpcs --standard=psr2 ./src
  - ./vendor/bin/phpmd src/ text codesize,unusedcode,naming,phpmd.xml
  - ./vendor/bin/phpunit
